---
  - name: .SSH | Provision private key to remote
    copy: src={{item}} dest="~/.ssh" owner="{{deploy_user | default(ansible_user_id)}}"  mode=0400
    with_items:
      - "{{keys | default([])}}"

  - name: .SSH | Provision public key to remote
    copy: src="{{item}}.pub" dest="~/.ssh" owner="{{deploy_user | default(ansible_user_id)}}"  mode=0400
    with_items:
      - "{{keys | default([])}}"

  - name: .SSH | Authorize keys
    authorized_key: user={{deploy_user | default(ansible_user_id)}} key="{{ lookup('file', item) }}"
    with_items: "{{authorized_keys | default([])}}"
    become: yes
